---
sudo: required
dist: bionic
env:
  global:
  # auto vagrant installation

notifications:
  slack:
    on_failure: always


# fleet_script_tasks : &fleet_script_tasks
#       script:
#         - python --version
# fleet_install_tasks : &fleet_install_tasks
#       install:
#         - pip install -r requirements.txt


matrix:
  fast_finish: true
  include:

# =============================================windows=============================================


    - name: "podman-machine  Python 3.8 on Windows"
      os: windows
      language: shell
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
        - choco install python --version 3.8.1
        - pip install virtualenv
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
        - python --version        
        - pip install -r requirements.txt
      # <<: *fleet_install_tasks
      # <<: *fleet_script_tasks
      script:
        # travisci git bash support
        - |
          if [[ ! -d "$HOME/bin" ]]; then mkdir -p "$HOME/bin"; fi && \
          curl -L https://github.com/docker/machine/releases/download/v0.16.2/docker-machine-Windows-x86_64.exe > "$HOME/bin/docker-machine.exe" && \
          chmod +x "$HOME/bin/docker-machine.exe"
      after_success:
        - deactivate
