---
sudo: required
dist: bionic
env:
  global:
  # auto vagrant installation

notifications:
  slack:
    on_failure: always


# fleet_script_tasks : &fleet_script_tasks
#       script:
#         - python --version
# fleet_install_tasks : &fleet_install_tasks
#       install:
#         - pip install -r requirements.txt


matrix:
  fast_finish: true
  include:

    - name: "podman machine qemu kvm libvirt Python 3.7 on xenial amd64" #OK
      dist: xenial
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - python --version
        - pip install -r requirements.txt                
      # <<: *fleet_install_tasks
      # <<: *fleet_script_tasks
      script:
        - sudo apt-get install -qqy libvirt-bin qemu-kvm #Install libvirt and qemu-kvm
        #Install docker-machine
        - |
          curl -L https://github.com/docker/machine/releases/download/v0.16.2/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine && \
          sudo chmod +x /tmp/docker-machine && \
          sudo cp /tmp/docker-machine /usr/local/bin/docker-machine
      after_success:
        - deactivate
