---
sudo: required
dist: bionic
env:
  global:
  # auto vagrant installation

notifications:
  slack:
    on_failure: always


# fleet_script_tasks : &fleet_script_tasks
#       script:
#         - python --version
# fleet_install_tasks : &fleet_install_tasks
#       install:
#         - pip install -r requirements.txt


matrix:
  fast_finish: true
  include:

    - name: "podman kubectl k8s Python 3.7 on bionic amd64" #OK
      dist: bionic
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - python --version
        - pip install -r requirements.txt
      # <<: *fleet_install_tasks
      # <<: *fleet_script_tasks
      script:
        - | #To check if virtualization is supported on Linux, run the following command and verify that the output is non-empty:
            set -eo pipefail #safety for script
            if [[ $(egrep -c '(vmx|svm)' /proc/cpuinfo) == 0 ]]; then #check if virtualization is supported on Linux, xenial fails w 0, bionic works w 2
                     echo "virtualization is not supported"
            else
                  echo "===================================="
                  echo eval "$(egrep -c '(vmx|svm)' /proc/cpuinfo)" 2>/dev/null
                  echo "===================================="
                  echo "virtualization is supported"
            fi
        - | # Install kubectl
          curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && \
          chmod +x ./kubectl && \
          sudo mv ./kubectl /usr/local/bin/kubectl &&
          kubectl version --client
        # Install podman
        - . /etc/os-release
        - sudo sh -c "echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /' | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
        - curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
        - sudo apt-get update -qq
        - sudo apt-get -qqy install podman slirp4netns #https://github.com/rootless-containers/slirp4netns
        - sudo podman run -dt -p 8000:80 --name demo quay.io/libpod/alpine_nginx:latest #create a simple Podman container running nginx and binding the host’s port 8000 to the container’s port 80
        - sudo podman ps #
        - curl http://localhost:8000
      after_success:
        - deactivate

