---
sudo: required
dist: bionic
env:
  global:
  # auto vagrant installation

notifications:
  slack:
    on_failure: always


fleet_script_tasks : &fleet_script_tasks
      script:
        - python --version
fleet_install_tasks : &fleet_install_tasks
      install:
        - pip install -r requirements.txt


matrix:
  fast_finish: true
  include:

#   # =============================================macOS=============================================

    - name: "podman-machine podman virtualbox Python 2.7.17 on macOS 10.15.4 osx xcode11.5"
      os: osx
      osx_image: xcode11.5
      language: shell
      addons:
        homebrew:
          packages:
          casks: # Installing Casks
            - podman
          update: true
      before_install:
        - pip install virtualenv
        - virtualenv -p $(which python2) ~venvpy2
        - source ~venvpy2/bin/activate
        - python --version
        - pip install -r requirements.txt                
      # <<: *fleet_install_tasks
      # <<: *fleet_script_tasks
      script:
        - |
          curl -L https://github.com/docker/machine/releases/download/v0.16.2/docker-machine-`uname -s`-`uname -m` >/usr/local/bin/docker-machine && \
          chmod +x /usr/local/bin/docker-machine
      after_success:
        - deactivate

    - name: "podman Python 2.7.17 on macOS 10.15.4 osx xcode11.5"
      os: osx
      osx_image: xcode11.5
      language: shell
      addons:
        homebrew:
          packages:
          casks: # Installing Casks
            - podman
          update: true
      before_install:
        - pip install virtualenv
        - virtualenv -p $(which python2) ~venvpy2
        - source ~venvpy2/bin/activate
        - python --version
        - pip install -r requirements.txt                
      # <<: *fleet_install_tasks
      # <<: *fleet_script_tasks
      script:
        - brew cask info podman
      after_success:
        - deactivate

    - name: "podman kubectl k8s Python 2.7.17 on macOS 10.15.4 osx xcode11.5"
      os: osx
      osx_image: xcode11.5
      language: shell
      addons:
        homebrew:
          packages:
            - kubectl #kubernetes-cli 1.18.3
          casks: # Installing Casks
            - podman
          update: true
      before_install:
        - pip install virtualenv
        - virtualenv -p $(which python2) ~venvpy2
        - source ~venvpy2/bin/activate
        - python --version
        - pip install -r requirements.txt                
      # <<: *fleet_install_tasks
      # <<: *fleet_script_tasks
      script:
        - brew cask info podman
      after_success:
        - deactivate
